# Generated by Django 4.2.21 on 2025-05-28 19:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nymuser',
            name='email',
        ),
        migrations.AddField(
            model_name='nymuser',
            name='mnemonic_hash',
            field=models.CharField(default=api.models.generate_default_mnemonic_hash, help_text='SHA256 hash of the user’s BIP-39 mnemonic', max_length=64, unique=True),
        ),
    ]
